#!/usr/bin/env ruby

ENGINE_ROOT = File.expand_path('../..', __FILE__)
ENGINE_PATH = File.expand_path('../../lib/spree_paypal_api_checkout/engine', __FILE__)

require 'rails/all'
require 'rails/engine/commands'
